/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SalApp {
    }
    interface SalInput {
        "placeholder": string;
        "type": string;
    }
}
declare global {
    interface HTMLSalAppElement extends Components.SalApp, HTMLStencilElement {
    }
    var HTMLSalAppElement: {
        prototype: HTMLSalAppElement;
        new (): HTMLSalAppElement;
    };
    interface HTMLSalInputElement extends Components.SalInput, HTMLStencilElement {
    }
    var HTMLSalInputElement: {
        prototype: HTMLSalInputElement;
        new (): HTMLSalInputElement;
    };
    interface HTMLElementTagNameMap {
        "sal-app": HTMLSalAppElement;
        "sal-input": HTMLSalInputElement;
    }
}
declare namespace LocalJSX {
    interface SalApp {
    }
    interface SalInput {
        "placeholder"?: string;
        "type"?: string;
    }
    interface IntrinsicElements {
        "sal-app": SalApp;
        "sal-input": SalInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sal-app": LocalJSX.SalApp & JSXBase.HTMLAttributes<HTMLSalAppElement>;
            "sal-input": LocalJSX.SalInput & JSXBase.HTMLAttributes<HTMLSalInputElement>;
        }
    }
}
